apiVersion: v1
kind: Service
metadata:
  name: secret-manager-controller-metrics
  namespace: octopilot-system
  labels:
    app: secret-manager-controller
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 5000
    targetPort: metrics
    protocol: TCP
  selector:
    app: secret-manager-controller


