#ENC[AES256_GCM,data:qiyYd23OC/86TDJfKVjcq0PJf9YxABl7wnNuQOTyG6HS8R1Yu4MNSMDFd77+q1rGfWpFI/fbr51JuT2X,iv:uF5moFwHU+sg6pJftVc9BXs6V0+xz+mUIz5/jOOcKOU=,tag:Ap4AWK9SM3myYb42L7K4IQ==,type:comment]
#ENC[AES256_GCM,data:8y2AVyMCUEZA7ZCC33DbjF7M1nIkOuZtM3chftCwBrA6Zs+0mKNIjJJo,iv:fIalWvjGyqGX4HGRIkTYfvIkPDDNUdxazSVzgaJGHLs=,tag:StrtlA3D7UlcdEK7dXBQqA==,type:comment]
#ENC[AES256_GCM,data:OXsrmEipv2X4SkHQNx4AadpEeGKtuT2lpDs=,iv:NROJEOmmIOiQNPfVfmPQcowFU1q6v4mu0tcJTiRM3qw=,tag:/eQNC0oegVZZwlva7sr+9Q==,type:comment]
database:
    url: ENC[AES256_GCM,data:kF57eH2ZhYZL24d8UKjsx7yI7o9f/zHVw16CrLniSdI3cWzi4yM7DNnk2vpgVge2cjyBL6Ip57Z6LfeN,iv:dh4eNSNu8Q+tFpjUTm5L53LmQ4je/A1/06uUQq4vHhA=,tag:tx1DhWWgZVSniED7a/MUPw==,type:str]
    user: ENC[AES256_GCM,data:3dXblR/IiOY9mI7S0a4=,iv:2Ql9ljNABO/UR/HsDKgGXeWz6PWyODKAh2lCCB53Ew8=,tag:nl19TV4uameF2MLbk5m/OA==,type:str]
    password: ENC[AES256_GCM,data:nX1rNcp6+GeTkevila3Xvtegercu/6g=,iv:WHkH+Id/wQQpsNme912xfUQxhb2glQcg3FXv+DBsOxs=,tag:F+PqhJ7TME33hzn4Pl7Y7w==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:bjL7JR7kQ9gI/mTurIr0BJQ8LycN,iv:q5L/Ybf6OA1/TJfiom14J3eNZji939KpPTeYDDkWz/w=,tag:/PsrXh9TrBNLOcDM9c38iw==,type:str]
        external: ENC[AES256_GCM,data:FqjZLSA8dPqh+7+IGlTZgVZRi7s=,iv:BgGsH+3BhNXlZRHexrxzEvwWok/JhdQKKrUHBuBA6pM=,tag:av75m3L9P5yVS61aQVXb2w==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:n1sYZFBM5czmCT12XEYFf1A=,iv:r99tOsgVYn4aSfxOjL7flfOGc/MB3rIcgR/i6ZsOmc0=,tag:KY1K3dbj8iACF8vFSwFN6A==,type:str]
    client_secret: ENC[AES256_GCM,data:9Az/IhXOCgC0vhegxL50N9w3YbVs,iv:dXhLqaLffe35WxzRj/HcKwNh4xpA1ZQTDGlVT6Ui4Xc=,tag:o+GqapyWvlx2nw/JrjHF/g==,type:str]
encryption:
    key: ENC[AES256_GCM,data:ggakqq0I+qSwxii5eoh0EQ01k7HYA5qBoJFfSHASObhEng==,iv:j1r5wDbI7fS2MTw2Ntfoca/po20mf3u9Re4W0fJaClE=,tag:P9Vx3hK5okT3XOh/1Lxzqw==,type:str]
service_account:
    type: ENC[AES256_GCM,data:byQaaVIa3lIOmEBoDNVk,iv:SJCZ8WS65Wgf9AuuCOnyxwuhvOSdzjrvfyFxgysdb8Q=,tag:JDcySd8csJm80U2PzGWaTg==,type:str]
    project_id: ENC[AES256_GCM,data:NJoNv51fMaasrs8=,iv:by7+xvw5aaeH0x/794njZJynCLVWEtxyVSYsmVZy7Xk=,tag:ZBGuJeb6E6R51OqWJmWvOQ==,type:str]
    private_key_id: ENC[AES256_GCM,data:dg1w/JHcykqYN+5T3g0=,iv:LvEjUaG34AagxbpOwxJahOxbxzBA5dGcASUn33y0EcU=,tag:vDEDHxfsTl1fpQHPjwMCAA==,type:str]
    private_key: ENC[AES256_GCM,data:ylRki44Jls67XbldPwsdgX6AAXJ/tqVGFs8gCcW0uWFz4bkcV+Pd+ivtAcQ3Shba51kH+mH7SNp314RWquIbRHR/s+CR+YcikCQtoejvIXDDDE1VEXkX/Ihq2qk4XMX6OrihFu8yXdAyJ+h/tg==,iv:WVt7v95mKJAvxedDJHQoLPHBhjo9Y9SkUxetMcioxs8=,tag:73rtLTYFvyZTZKZCIJET2A==,type:str]
sops:
    lastmodified: "2025-11-15T21:03:35Z"
    mac: ENC[AES256_GCM,data:dvAovHkyHspzapHlXMx9q0l3xrHE9Ti38LywHIyg7zasWmPdzkEI5tGjD64cFZ7I4zyqpGk2EzuSBC2NVUoi6C+875ByJQEiaSrxK5CU6aoa4WJWDD6FF0hO1ZPffW19tilJEy7at8Ba9Epp4+JxnzXrPvbsR31vDjLlWoaHSO4=,iv:xxbLCT4Q6bgqqBo3qsmxMGAKiBrR2J39xoGWlJ6M430=,tag:vc9eH/XPPlndBDz9qUt+YQ==,type:str]
    pgp:
        - created_at: "2025-11-15T21:03:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUARAAkIzMYuDy7wBmwjzjaQzo7hFxEXe+Cd9fqGb5C88saXXV
            VA7+QhMz9sIy35DH6Ug2IVgXny2Jx0dAV1oOVI3YioBirbNys3Mlt7/QJDQv6YPS
            +noteAGtupmSxoO8JYxqwjuryny2tMpELoEr03zfKyk/RyBlX4MYdhpNQreZrCod
            3Cv632Um0IWbMCT2/aiqJzD/lw4WNi8HY8O9XvEXruXlvtij2k5EANz7YyViryie
            HjgGQnJ2sE9T4fcdiePNPhiIiZQfrmEc9H/Ck/zqJ+BYhMiLe5E7bijA+At60d/S
            wmuaDiwcxwG8lCsiJGzGnxx1wQReUbY9oDIlqQwmiBBQUFnfi0UC43+KRQMlmDQi
            OBOI15O/wTeUbzNay+Ifs6CZ5QzyjJY8ykPssX0yCVJ3rUnI+x1KqnQZ3Kv5MAIo
            6sPROzhSpnKn9uHX3kUNhP7X2sD8oIthNKqvM4tB7zNfSKNndBCahGTO6Ambxt6y
            475L/75ZNQ/dUzRNFcJMl/cWR+jPiJrrw+eiDstXZ8FG71KOJOPzc5JASIDBlNZM
            DNBLSw4nNkl7yPIBn7yrFSfr3xUnl4TPeAoP6vIzhq+3U8GZG++up7JW3TvXj5zB
            Mgj1jJufLYr+oNwGaRteNJrBXrJsYY4oKGz5p1RgfK3GORVp7j4x8v6wmsmtWITU
            aAEJAhCE9aQ+WDIuWE1UaW64JJLMkfkD4bmuKe2oXfLOcyOruRONQgY5UBrTrnCc
            gA15M8wwu8TDQnMGwiUgAUvv6rrnblH57o7dnQYFYpLHLoGw+2XEiC//+YYDozwG
            FyBgp7EuuIG6
            =Jccw
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
    unencrypted_suffix: _unencrypted
    version: 3.10.2
