#ENC[AES256_GCM,data:5UTGkWeHELTn6Ju9MriijfWPMZy0/Ue37t8POj7IRrSyljyR3cVfesVCzuiSaM4Ux+rbqsxFNvfuliwO,iv:uF5moFwHU+sg6pJftVc9BXs6V0+xz+mUIz5/jOOcKOU=,tag:CHIj4Cyd7uqFIGU0d5ZrPQ==,type:comment]
#ENC[AES256_GCM,data:U2MBevaCNJ5mQ20lmb6s5Mjjt18O/bAvLbT1LzfYAPuDqMm4b+t+egZ7,iv:fIalWvjGyqGX4HGRIkTYfvIkPDDNUdxazSVzgaJGHLs=,tag:Mf3unC9BP1G/Wy6XGFsmPw==,type:comment]
#ENC[AES256_GCM,data:6vxajNNmZ1LZw87YZ6r7ZQ6CGrmnlwf7AhA=,iv:NROJEOmmIOiQNPfVfmPQcowFU1q6v4mu0tcJTiRM3qw=,tag:YqeTzRT4MkzuX1pWMu75vg==,type:comment]
database:
    url: ENC[AES256_GCM,data:dOU26K55m3eFGGCFgdwE+jQVfLRd5IHX6hCYyGc0hg4Jh3az99ItkqEw1+gMtBxKeesTCRbTOUPcfBoU,iv:dh4eNSNu8Q+tFpjUTm5L53LmQ4je/A1/06uUQq4vHhA=,tag:TTIx0U6O7mpxKsXUaEgBkg==,type:str]
    user: ENC[AES256_GCM,data:pQx/hLsNqodjUFL1q/8=,iv:2Ql9ljNABO/UR/HsDKgGXeWz6PWyODKAh2lCCB53Ew8=,tag:WS35JDZCY3resxXAaWMd0Q==,type:str]
    password: ENC[AES256_GCM,data:NTC0Ybm69C/DKk3oG4w856f/xi3B4bU=,iv:WHkH+Id/wQQpsNme912xfUQxhb2glQcg3FXv+DBsOxs=,tag:02RE4EEace6g4VcEzUvhUA==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:+HKJMgjMlnLJ4w5speQ9cqStshj/,iv:q5L/Ybf6OA1/TJfiom14J3eNZji939KpPTeYDDkWz/w=,tag:DLsKAUohX581FbKkbKQexw==,type:str]
        external: ENC[AES256_GCM,data:xaVmKIuroyLrhv1UV4e5SYudtR4=,iv:BgGsH+3BhNXlZRHexrxzEvwWok/JhdQKKrUHBuBA6pM=,tag:mN2PHgCFfRAdkJIGxbXVvg==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:jCiJJ3SBh339JG+NvN2mljY=,iv:r99tOsgVYn4aSfxOjL7flfOGc/MB3rIcgR/i6ZsOmc0=,tag:bxKyr7xpyIe8iV5X6M4DZw==,type:str]
    client_secret: ENC[AES256_GCM,data:shsRkRC/jdX8ZO8RdBcrzhf0V8RF,iv:dXhLqaLffe35WxzRj/HcKwNh4xpA1ZQTDGlVT6Ui4Xc=,tag:Gqks+k1WWg9oO0e7CQz/DQ==,type:str]
encryption:
    key: ENC[AES256_GCM,data:ONueJpBcOWOabrLiMRj0gDDIo+d+aDKTQUf9FVsWI8/8hA==,iv:j1r5wDbI7fS2MTw2Ntfoca/po20mf3u9Re4W0fJaClE=,tag:wQHyZF++TVv7ejY6crfqcA==,type:str]
service_account:
    type: ENC[AES256_GCM,data:WJW4eBZthHtBIDjubXoJ,iv:SJCZ8WS65Wgf9AuuCOnyxwuhvOSdzjrvfyFxgysdb8Q=,tag:KM3r02ejckAe2ZD+Ss9aGQ==,type:str]
    project_id: ENC[AES256_GCM,data:5l0eOc/MoouPDzg=,iv:by7+xvw5aaeH0x/794njZJynCLVWEtxyVSYsmVZy7Xk=,tag:L8XNaAdihbE09sPNPNbr9w==,type:str]
    private_key_id: ENC[AES256_GCM,data:nNweCIixly7tOslCj1c=,iv:LvEjUaG34AagxbpOwxJahOxbxzBA5dGcASUn33y0EcU=,tag:XcxklS5AuxK37rWZ4qnRcw==,type:str]
    private_key: ENC[AES256_GCM,data:pj3UFO3z9W+jeR9x6KcOwGmTjdgojdkL81HWCegH+9Yq18kjLdrkFNnQgbrXOB0vWfVGFU8kCEtXQVrwsR6LUfJtv6v2GP+evQtZdIRj3yJT/98CIiGDO8lGVV83IKdakto9g5UyzJdf+CVErQ==,iv:WVt7v95mKJAvxedDJHQoLPHBhjo9Y9SkUxetMcioxs8=,tag:hVnbljaPhfCQgaW5B8KEnw==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:Rd4fF4J5WmHSxDva9Xk0Yf2QU4Se8CCCoVYLnrKx51bHXk4bdF8lKxm3FxlZxLBY3M3A3uqmNPr2RWUKcqYiXFdmJJHCqNO8J/y8ugqtOgavKNQ/7h7kgf4qX1vYWA8Fkipt3ma/4bVZUByHnx3txbIfoPJ5jDw/sW1MgLcTYAQ=,iv:TJQuZlrAI7oLfetGjU+UxWwG5JpmJm/zcoAb9kYAdrI=,tag:3aNtT9ue7opK2TU4IX8h6g==,type:str]
    pgp:
        - created_at: "2025-11-28T01:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUARAAp05rA8c8B62+gdyr1F5cRptCvk8BI2GiPmUzaward6IZ
            MJevSOIpMdx1UTZcKKtI6Y3O8oI5CSGumCY8Z+07KcTtvTY81e9mVTRo1RKai/EH
            FF/nRYGB2gvvgBUeP1MTYk0wWdgItN+k96zU3p5bHI1w0jPgcoDjwHl6iO4BGg6E
            Q9YlmnReNdRkVmUMedbWvGdEVbO1+yUljwxPtwtZEE3oZo8yz5hEOrdanOtqLvUa
            VxGW0rbJKFtmwXCLAKXaFuEX5Ayonl6kduc/3jmIzeI4m6ojvqVS1X8zXMUQDI7t
            tksAMVd6cH0ax5gBk7gS5aBqcZB5dgcHBW7qrwDm8gpX0ng3/VsbVa5qO9wpXl9v
            93oSQqeSKjRNeYVsuk6zkuOlBsfadYIMa/3tbWOiwKY6qN7FQGUrvks7NrAeNqWN
            MtBIwSV6L+ie6VdEP1E0T838eNQ0O02JENTZdJ/GIxrZXVRBfyNQTKI9z2K9Oyrv
            fxWbCNE4E90s677jGocNOuTAk/aFs40aKrlnIRwY81NYdcLO7Eppfbe78qlBUORk
            j7MlEEWGhrrHzI/XJFAFzy0WwhcwyclOaWNhzmuUxT0Perifqh+2gKGs2Mshq7lt
            MQLmD0Ag8w050jCrRzJ71dOkheJZnMNF8FJe2dkfUHm5p53ZVpi3tZf6As2Hh7TU
            ZgEJAhBCAvl/cUJvYSg0MMLQlMXE8kKcRtKn7x7dSAOiw8QnAuetKw/0A5u7ZOEt
            NqtOIUxHzTmrXb38jz8AM9qLwETuE/WSo8rIFzNyE1jSG9w7AM7l/FGIpUtWQY5F
            lAdH6sLIbg==
            =ZvoH
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
        - created_at: "2025-11-28T01:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ/+OmCbowyNvoJEOQpAm14Ma9OgXpO/U234eOMgJ46TQnrU
            ZujT1/d5lChKBfzBIhsNT9K87Z0ZbiqjaiLRolEBaRKaccTLuFnNaMNwXzTXBWJS
            95q7xBbgl420zy18eOqtx48JMPoauqWNFZW0j1hwEA/PtOPy+LJh68FzW/DiQ0sZ
            vFTrgF/jlF1Bog4HSCPQPfKRqhbj9dz6l5HrGYUqwu4gvcKvdi7X7/dW77xi8Y1u
            v77CpBqEiJBowIv9XFRH6htW4icfzjVyNQx+qQ4s2cc40BDR4HphD1p5L/3k0gUD
            YsTbHITfjVn179678UYif037PBkztfv/YGlbVHDmoZ6gWXY7i0D0X7VVmw4c5WhS
            o9rqrM1wuXfwgDxf29Q0dSH5cmMdORweHRQG1FQWp5u8dcvu3RVRjZCdKiLjykJT
            Dukrauxw40WHAnl3Suvb8pLz8ZhHV/wNm1XaU7wZ2K6Xr80xpDZArJ7ENJ8uS14S
            T1C3FxZsL7GC2yuhz9Gor/C1EVvHbRFCdNwj3YFN2R33oKJeuREmymJ/tCd0NMe5
            PXSRspslNboddtcj0jbO6wpjaI9WdBtI7UteYqnNLc+VFxQf78mbsigZfCmt6KeV
            xSQldKz5QB6/KNyTNAarQoGnPO1WselJjBH5tSUQ4+GZSuNPqeeLZ9ovIdxRv9vU
            ZgEJAhC68nUJ6YjMl4stUXypMrnn885TzAcqkZxXpQWXGaVSoOE3K1B68KAvGav8
            gnWyh0Zzuzngz5vkUuMRFNu16OkcJzIKEeVcOEYDOCtzem97yTzo5Ff1CTLn12O5
            bc7G3DMZdA==
            =mSo6
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
