apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-controller
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager-controller
subjects:
- kind: ServiceAccount
  name: secret-manager-controller
  namespace: flux-system


