apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-controller
  namespace: flux-system
  annotations:
    # Workload Identity annotation (uncomment and set when using Workload Identity)
    # Format: <service-account-name>@<project-id>.iam.gserviceaccount.com
    # Example: iam.gke.io/gcp-service-account: secret-manager-controller@my-project.iam.gserviceaccount.com
    # iam.gke.io/gcp-service-account: ""

