---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-manager-stage
  namespace: stage
spec:
  project: default
  source:
    repoURL: https://github.com/octopilot/secret-manager-controller.git
    targetRevision: main
    path: deployment-configuration/profiles/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

