#ENC[AES256_GCM,data:6mDzC+kjMKZfi7Ki2+pMlX2aykSRvMB5FVNC3X3QjEII5ywIptw8EwrK9SrCuRvbw2xHoGBXLOEE2RQo,iv:Jf+f5Yb7qydijPwlZb29dGhRENepo7fE0fJc/VC6UPU=,tag:lEJR9lV/OMVODq3C0Ae8nQ==,type:comment]
#ENC[AES256_GCM,data:/Su6bqX52L2U/Ifu8eqmNMvbcVP2zK+ynikJ387DP1t5KzGyKMAGJ51Z,iv:7nCV4LuX/33dU6TC0+/EHKzQuXyFjY7uNn2repbZ+Fc=,tag:MK/41w+4IpUPeuM4W9nYWg==,type:comment]
#ENC[AES256_GCM,data:ybfVgVZVrY/qHsEeFjzCtDlx58ldXRNLUE0=,iv:GXaPB6qeDhS7uwYsBqfw0BHIygZnLMdC2+p6LgSqU30=,tag:lDFgsdSZhccg7VVaPxThbg==,type:comment]
database:
    url: ENC[AES256_GCM,data:buTQz19LadJZ03Q82jbuI7nVEw4jAFRxLmXZtsyv+vRYM5zg41CEzhlK7t4nvGqjU9QZk5O1/Eb56Eih,iv:rfzK5g5I+B7gwa50pgTPWsslNn0eeW3qUeONBe8TysU=,tag:dLb35GtPBatqxXyheRXpUA==,type:str]
    user: ENC[AES256_GCM,data:EKaLNjdq3vuHyxLLV5A=,iv:DgyJLTIROcirVuPA4Gd+GB6L3P0RNrwPYACc7BTqg1U=,tag:zBqfcqoP9BA3TZwSyorzVQ==,type:str]
    password: ENC[AES256_GCM,data:OGbQCqge1x3hQGAU5cvNICLDbM39kcE=,iv:CCelWF5W7okAR2Y6XvK4PvdRjoQJCvfWUrc7SDm8+Y0=,tag:Ig+Bbp5fStsLV6mIk4vTVg==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:thCau2KnzBUDsuPrtu8eqvmYFuPt,iv:2yFGTjCDf3fJjb+7u/el+7g2uyONISWgkV5mcuPXxaE=,tag:1LupfWSvlZ7QUyngD/u1vg==,type:str]
        external: ENC[AES256_GCM,data:G/bHJ0rlPmaWMSqM6Eb/Tl1w1NY=,iv:jY6/jABUUjwu5FIN2R5tze53BCDRhuyrjzHl4oJUJAk=,tag:OFQmVehEda79vEa/qhBJuQ==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:7a7yIQEGryVSHAEipoKtiTs=,iv:Wg+gURSfdnwh754DBiO+J48/aQwHji/SSLQxarXj+8s=,tag:HOtAQ0FvM+BHSjgYMaToDg==,type:str]
    client_secret: ENC[AES256_GCM,data:pooEMaglHox/XwJwxiL/OpY0d3bW,iv:4kNd7q33ZPw4ald7X8AdIlnynt1cikxutATX9GBPhJ8=,tag:3celFSZkuoX9hlEvnW+OFg==,type:str]
encryption:
    key: ENC[AES256_GCM,data:VgUupYpTZ8Akbds4/eeoUOGDKsLC4gYB49ocYf3g/VmTWg==,iv:QYSn+xZJpT1HhnyMZn89yQhYgXGk2OjqKEjNbPIUMus=,tag:tbCop0IvYIk5K5kkIMQnwg==,type:str]
service_account:
    type: ENC[AES256_GCM,data:irhNj+jbqMlvwYXzfZw/,iv:koNdEJlK8TtvXfA1HWsXeMfqiTJozBji7PKipsOpT0A=,tag:Thna0Bu1Ld1GEuIJBmrO6A==,type:str]
    project_id: ENC[AES256_GCM,data:0PavlKyspSRc6YY=,iv:Cz6ximf7avbCdJEslrWJSsZh9Z44XvEoqLUdYXY3z5Y=,tag:aQYUoDV/ExZX+UHyw50cTg==,type:str]
    private_key_id: ENC[AES256_GCM,data:IltLoHUWd2il3k/Beag=,iv:Eq6+p1k66fUbzglA1QjDVT3TS4Q4n2W+l4lVArzzGjY=,tag:mjPshWb2Q0F+LNb687TN9Q==,type:str]
    private_key: ENC[AES256_GCM,data:y9dvUOB38gYm3GItywbXSaR9dFp7YglR6KRfW+3/ckXWk39iENP2RyqckUERTAm9ie9bS8NSuw617o5ob+vpuqHmg128FsTf9L07q8OI+0/sW0zhFMbs57dMbDLngD4TO6yvBQrj+2Q0rJgiag==,iv:WpjILEWtBCliZJSND0n2vNSmSaXd9b+dsl3oRrBqCNg=,tag:bysid037zELI581QD1Ef3g==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:+zdyDkwTbgdtdvZacrlfmQORd9J4knTshjNW6oKJxEfGOdFPR5NNKknuKyqKDiH8J3aBXWpfi+uN5rr2yICHnRLJ5tbk+UwORv/sAlvNj2zXvvcW3PsjTNztCxzTgQPbweCuhBuAUdPrRCttclkuzfFazqUQV7ZnUJNjjwb5ZwY=,iv:pkcIPdDs+ZmwuoB3zUQS6zk78iyyjL94uPJykeapTIA=,tag:yC/mnCvyvM1wO1HmdLhCFg==,type:str]
    pgp:
        - created_at: "2025-11-28T01:13:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUARAAjNW5ksHaKWulZn6Bz9Xv/OK/PrIAEATuQoLONa8V2v+u
            AzuUFIZHuQVl80IMhFWAF/SpgKVaWlBzJvSCgi69eXD29txU4OZW/a8+W4hOtjSb
            KVFIhih5Ga7dnrhhTULgwHP0hLKjhPqgUZDaBaNfcx05DX/lmKo3XRrb/zigGFer
            dpx2qATvkAqQvRNJlj23GXnl2esXCp9qCUdQjduE9sHCwmp+ONGdk4hddX1VNFwg
            20Fr7Vcr47ttzxfa5OtAJywtU8F4bjkvqY27vIuLmq799bCd+3pYWNStmlTU9e0G
            yE2BNI/aGp9Uudpbk+XEnVjr+8tttVG8Z2K+ooZtRSPhB6sD0gIjCaEsIoZLLlIm
            +7cy6NJxIMahDlcC0vgQHFWUEi49zOEQ4Y4Ui4wMdnSdwIWqJt4CFc4IEc38zWlH
            19/whvFsKsPbuM0qJYgDX8QmKH5Ve4n7LC+RipU6zCIP9V8lIIx8AWB8om84mSLD
            WVm0U7x4PbbBsLUQmTLx8PDnISvCu7cvacbjJG5+xN17JbBrKUnJOp/Gwndg6QYb
            ikgsHkOQ3DiNrU0ShULmBeggZLRIZ7tdfTwMOzsyKBtm8e00PoteK1MN/ObHJfoC
            Z870VAQKeNIFQCTHodIdC+asyVn3k2EnI3qYvF5Cjct9I32BqjbipPVT6csc85HU
            aAEJAhDmKc/mrKakpsZFmFB+WKMOefbYlg4sc8nlA+jZMU/mL6i2/exn8aeXC4fS
            sGD+GfQSoUdYVUDxtjIrnaUMIMS+KFaft/+z2I9xVrv0DmdyWLb2HbZ0uiPcRG62
            PsNzWGh0hVPg
            =NNGO
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
        - created_at: "2025-11-28T01:13:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ/8DoXzDbRIDOGazxgut6znA6U3vZ0b9VFOGTmZFbBrZ+KE
            M0sISrYayfGdAMLYHr17P321bKTWt1s7PIy7urAdQ1EhcuxBtk9p9Rc2g+6W+i75
            ay1Uwzs3fPpetMeuErRCW5zCysgwcPSoS7mjOZt3FSCWX3r7JlesziNeaX1MVTU0
            3ERRGfMbZMrvk1Y4knOfnoAtzoDEe7I4pY5Amcr3HV8oZTaqUTWO8faYtCAeBCdm
            mY45r8J4RP7BWT+D/R3Tz1bpNMFcfmjRo8DfBDKvO4orS5c0o6vMJBbAAiM9YTRL
            cksmtozx0yu52Szb/LxohLbPCaC6KnxGA4qTLkUSyut5ED/K0beh7T885i98jVj4
            tKwV2n/35b9ODdSpOoo+eco59zSxUOaZlp+KbzWjyFtlXzvWAq9cMCLvcUqGS/eQ
            kILOVQZMvZMDsddiAHnrSmWDTKVIBOLCVVZVb812LL9vgELc+4+3po3qO3GfpcOe
            3BGeib6jWaWCbMpqljQe8icBYL3LBhWEByt9NeJ+WJc+SqBl/X2xoaLWZfg/iPBd
            sy6Og6f4+nXrMhqAk8IzfyD4CIO8cEjzsC6yMWvrQmqz1k3fyDF2QCUW2YyKVOzv
            70BiQI15LupDZV84xXrNdCljftd3JHclPePSLqNST9AxCBk1CYLnw0nBumwb1P/U
            aAEJAhD7i97W8ROW6M7c82K7OhtoEUJPrDlFX1tZh6vTy05c3dV9b2/fSSQhg/eI
            ux4PvWcc7UwvfoYzr168zKQUhx2ICxUrFonI9phrGMhyjadCz828SSh77akmdIzo
            u0snvnS0qW49
            =O/Fy
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
