#ENC[AES256_GCM,data:6mDzC+kjMKZfi7Ki2+pMlX2aykSRvMB5FVNC3X3QjEII5ywIptw8EwrK9SrCuRvbw2xHoGBXLOEE2RQo,iv:Jf+f5Yb7qydijPwlZb29dGhRENepo7fE0fJc/VC6UPU=,tag:lEJR9lV/OMVODq3C0Ae8nQ==,type:comment]
#ENC[AES256_GCM,data:/Su6bqX52L2U/Ifu8eqmNMvbcVP2zK+ynikJ387DP1t5KzGyKMAGJ51Z,iv:7nCV4LuX/33dU6TC0+/EHKzQuXyFjY7uNn2repbZ+Fc=,tag:MK/41w+4IpUPeuM4W9nYWg==,type:comment]
#ENC[AES256_GCM,data:ybfVgVZVrY/qHsEeFjzCtDlx58ldXRNLUE0=,iv:GXaPB6qeDhS7uwYsBqfw0BHIygZnLMdC2+p6LgSqU30=,tag:lDFgsdSZhccg7VVaPxThbg==,type:comment]
database:
    url: ENC[AES256_GCM,data:buTQz19LadJZ03Q82jbuI7nVEw4jAFRxLmXZtsyv+vRYM5zg41CEzhlK7t4nvGqjU9QZk5O1/Eb56Eih,iv:rfzK5g5I+B7gwa50pgTPWsslNn0eeW3qUeONBe8TysU=,tag:dLb35GtPBatqxXyheRXpUA==,type:str]
    user: ENC[AES256_GCM,data:EKaLNjdq3vuHyxLLV5A=,iv:DgyJLTIROcirVuPA4Gd+GB6L3P0RNrwPYACc7BTqg1U=,tag:zBqfcqoP9BA3TZwSyorzVQ==,type:str]
    password: ENC[AES256_GCM,data:OGbQCqge1x3hQGAU5cvNICLDbM39kcE=,iv:CCelWF5W7okAR2Y6XvK4PvdRjoQJCvfWUrc7SDm8+Y0=,tag:Ig+Bbp5fStsLV6mIk4vTVg==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:thCau2KnzBUDsuPrtu8eqvmYFuPt,iv:2yFGTjCDf3fJjb+7u/el+7g2uyONISWgkV5mcuPXxaE=,tag:1LupfWSvlZ7QUyngD/u1vg==,type:str]
        external: ENC[AES256_GCM,data:G/bHJ0rlPmaWMSqM6Eb/Tl1w1NY=,iv:jY6/jABUUjwu5FIN2R5tze53BCDRhuyrjzHl4oJUJAk=,tag:OFQmVehEda79vEa/qhBJuQ==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:7a7yIQEGryVSHAEipoKtiTs=,iv:Wg+gURSfdnwh754DBiO+J48/aQwHji/SSLQxarXj+8s=,tag:HOtAQ0FvM+BHSjgYMaToDg==,type:str]
    client_secret: ENC[AES256_GCM,data:pooEMaglHox/XwJwxiL/OpY0d3bW,iv:4kNd7q33ZPw4ald7X8AdIlnynt1cikxutATX9GBPhJ8=,tag:3celFSZkuoX9hlEvnW+OFg==,type:str]
encryption:
    key: ENC[AES256_GCM,data:VgUupYpTZ8Akbds4/eeoUOGDKsLC4gYB49ocYf3g/VmTWg==,iv:QYSn+xZJpT1HhnyMZn89yQhYgXGk2OjqKEjNbPIUMus=,tag:tbCop0IvYIk5K5kkIMQnwg==,type:str]
service_account:
    type: ENC[AES256_GCM,data:irhNj+jbqMlvwYXzfZw/,iv:koNdEJlK8TtvXfA1HWsXeMfqiTJozBji7PKipsOpT0A=,tag:Thna0Bu1Ld1GEuIJBmrO6A==,type:str]
    project_id: ENC[AES256_GCM,data:0PavlKyspSRc6YY=,iv:Cz6ximf7avbCdJEslrWJSsZh9Z44XvEoqLUdYXY3z5Y=,tag:aQYUoDV/ExZX+UHyw50cTg==,type:str]
    private_key_id: ENC[AES256_GCM,data:IltLoHUWd2il3k/Beag=,iv:Eq6+p1k66fUbzglA1QjDVT3TS4Q4n2W+l4lVArzzGjY=,tag:mjPshWb2Q0F+LNb687TN9Q==,type:str]
    private_key: ENC[AES256_GCM,data:y9dvUOB38gYm3GItywbXSaR9dFp7YglR6KRfW+3/ckXWk39iENP2RyqckUERTAm9ie9bS8NSuw617o5ob+vpuqHmg128FsTf9L07q8OI+0/sW0zhFMbs57dMbDLngD4TO6yvBQrj+2Q0rJgiag==,iv:WpjILEWtBCliZJSND0n2vNSmSaXd9b+dsl3oRrBqCNg=,tag:bysid037zELI581QD1Ef3g==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:+zdyDkwTbgdtdvZacrlfmQORd9J4knTshjNW6oKJxEfGOdFPR5NNKknuKyqKDiH8J3aBXWpfi+uN5rr2yICHnRLJ5tbk+UwORv/sAlvNj2zXvvcW3PsjTNztCxzTgQPbweCuhBuAUdPrRCttclkuzfFazqUQV7ZnUJNjjwb5ZwY=,iv:pkcIPdDs+ZmwuoB3zUQS6zk78iyyjL94uPJykeapTIA=,tag:yC/mnCvyvM1wO1HmdLhCFg==,type:str]
    pgp:
        - created_at: "2025-11-28T00:14:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ//XtEE3e2wtC9+T68NEZD8XUdEmGL28WRsxSsDqRHKER/7
            rnrUHS9wtwX8Oet/ZaVdGgKLiGks6yi9aFWDUuLVqNUWfJx0Y50BurH7bnWAvlWe
            FzIA2Oc6yrMaohvIrXiVndeDVZBACqgEQSiuUBg+gHuKPeHMqaIparW8St+ow4/4
            2F7c+nFnZCUOxR5whiaJChHXDmeFFfDjrd+M05khstyxJlWxSp59bDveXx361Y5s
            ZoyOG3OQcoRvyHvltID6z6mmdUnWGg1UpF/O75Xes+Ec+Bkd00pjTNqI5KCB0YKE
            b/S1/5fmpoylSn5t0+tQHPZLFTq+DNgi5fPhJn7GPrPMgoSdyBO8EvZVqyZjtTcw
            px54wdfLU4Ecf0LTg03z/brey8HzWuJypzampBBhrPOvIb3PIDdmEDJdlTStuxQC
            QfpDeIEpC2QSUjIEAa4+ZIE2NmlKrrGOY7KPt9bq7f4HCMlqXsLtwXaADRnTvgHL
            TgMKlEdBRL4N2Oy7Yek5LVpg5jVw+ohpBkm/m3fhJRNqQyuPjdvdOkrpBVFGTsjU
            7DGAwE3es4RqH+9QdHhCMZX6n7lQ1aZr6f4b7uL/ZthkMxXc1K4fA97CVlvnqCqq
            NlSyTmXN6AFXh12tOPWQJKwlnJtBgQylIOnArgZF6QVCFwSi+9ibHqOXV6uA2RfU
            aAEJAhBnD6q2dMMpBHf/OLIzsc9bbs5vPmOLXp6OZBf2LfmI5YXauikoMt0IsBZn
            afbjufboHcyJL3lKSFYkhVUlfRkxbZOl6UFmITP/uZBSIGWb9OHkU4WHoItkZsDu
            l8uRykkuLiwl
            =dqJd
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
