#ENC[AES256_GCM,data:f10ZQ11pn1gvUtvVcQOFzwBbFnbraN49XFeKCko9UvXmC/uP9LIW5v55rccWvZNbshKE3HfewUQlazA8fJA=,iv:36jZGFEL3uhmpORDPOeSlEIBazUPpOfDQB9z2FovvVM=,tag:eLzMZ85mBv6QrbPX96Uq7A==,type:comment]
#ENC[AES256_GCM,data:kcyakyIQZYN1t3XEC9oDOp+cvfbqdMJdDCFpWgROoTkFI+I9LRpbxfgl,iv:ZguMX0bbMa/1nUCVUJ0d9QS4o0SpmUpaCmnUoJdrM+g=,tag:/6Z4cyS5Sj9HTxqr8cVZPw==,type:comment]
#ENC[AES256_GCM,data:IPw4seyg96iCOcNqpz7YNzbl3qOU9L7xOm0=,iv:RILbY3SHHEvbPIN2rRt2cny3n3ZygtEFMmSmsTm7QtY=,tag:B0iZsIa6eJc8SBxZLMPM/g==,type:comment]
database:
    url: ENC[AES256_GCM,data:ZwL16yqjQHWovPci06MPJh+qI3WEGngwRRIeCs8tPOcvn5qJPnMBb9dsczbSnY4TFq8xTkBgLISaQ8ULXIFB1g==,iv:tiJZPi86BhzLN9HuKeAn0Y+83g743equhG80GjoeTsc=,tag:drFJJguvcynuJUhuTIoyFw==,type:str]
    user: ENC[AES256_GCM,data:tsKwLlM/IsT2obwMJs/jPg==,iv:obxeaBSX7n+rIX4AUI9+hFykROa1nW9rY7cbSl04NE4=,tag:V3YJNk00sf7wxMTH8VI7aw==,type:str]
    password: ENC[AES256_GCM,data:7YJfeP/o6uHpj93/DI7K89ztcJI8Crr2vA==,iv:P82J70MZ5xBogGljA8JE5wD983lcHpMruOUqtKtSioM=,tag:DutDpUMAa9olsGxgUePYMg==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:0xvCzb0NUHH2MqzwLlnBBIvwwQh3sNc=,iv:X4QmD+s1MaZiEoEctfB1aAR6k5HMBVPqGNVuOqfGWDU=,tag:kwgFTHFDj6202d3A9KKZ7g==,type:str]
        external: ENC[AES256_GCM,data:xLW5kxa18HUAYE1Gi4zkojjOdnDTCA==,iv:+zkNibWP05eSQRe66bESMANTLGAFaZBbemxaHmR7IUI=,tag:7hcpl9f7UvWZNGtv0V8V4A==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:VDwzstjcRnIjV+FPK5qVcuZK/A==,iv:xoUO+1cO88Dfzn9FZYUfS0Pm4HcZtyNIDp8J0rF9tLA=,tag:XnUZniP20I7m8bk3M07Y9A==,type:str]
    client_secret: ENC[AES256_GCM,data:F+vNL8rp0nUOamUDa1yJkrrtoOmEcJg=,iv:uong2vQCA5GfpI1jeW8IZfmfC+XrDchLiJ2QLruc+XY=,tag:ShSizdineS+aTVVu3i8BeA==,type:str]
encryption:
    key: ENC[AES256_GCM,data:jSIdpBCjuUsjuUireoILb6XsWfP79YUTzV5STdauP2n85mQ2,iv:gMqNrrOUuzVjfUSu7hiZ8N4oEryeriw4pvY3uM0kvi0=,tag:moJLa1A+66UTWnI32qyXYA==,type:str]
service_account:
    type: ENC[AES256_GCM,data:BbN6sTVfILRgV1j5tgXL,iv:3i+NDWO2JBSPlmDuMR09qJ1VtGERuqcd3upY3/G6soo=,tag:w2Gy8aiNUUhJ6xgovyklmA==,type:str]
    project_id: ENC[AES256_GCM,data:D7/VSNBSb1Z0Fs0sYA==,iv:XHExPrndNpcJNR+HF7GO6l7A5PCcOCxU+2g3B3JiHvI=,tag:9B83NwQhzppDG9kMMyKu+w==,type:str]
    private_key_id: ENC[AES256_GCM,data:8ln1WCTaU5HRFUQxP7tIOg==,iv:vRIzFwDBBvFf+AMvv4F9/ygSSsHga9SB1OCk8h656DU=,tag:lVcsn8P165USniT288t8YQ==,type:str]
    private_key: ENC[AES256_GCM,data:XC1Jg9hRE8ACgc6pvP/powjxFt2+47JAyl0TyI+n7TwJfFXp/XwhLc8XDrcWhTJ8jZe97k6+IQO9zDsHlGVWeQO9ET8dAr+ap3TuYK1k8+ZXlvUgaLZThfUYY9mwEqqq26n7SQ4HPb05qJEYHA==,iv:qv4sbRs7gBnEj7X94wCvFjz3J3ENRFeK5DQyRRuAcvo=,tag:plybANCWKx5TwDCp1r0nGA==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:aM7AxODLeQez8QkUV+zpaZUgn9utWHXN7BchsQrktgQrsMsFG6uNiPP+I9zZz0Gfd76Q/xlK7QGdZZifw4d8vCtrFw2Oz55FDXhUlXkvXXuuhhqbWYjZ5x0iy8BiV0cjGhveb1OzBVBb/OaaANMhZoQtayNwuS4o8x0/DoygU6E=,iv:26hxcZdkwjPj75ykgClY0kGWIBj4Ffz42YZ5azgC16E=,tag:yWW3lkP/cMD5HFbeVcB2GA==,type:str]
    pgp:
        - created_at: "2025-11-28T01:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUAQ/+LWnxUFKrV+SYaPhFMFsNfOYmQKSph4JU5S5pF6xXJIuY
            qZH465E17mZC5X+bY+vJ7ONMFh4nflnBX+hF4RhIxcpkLPIf+c5A89Ojbg9SIhXz
            H+t/hcsFCovnQeDWiv9j61ud9s+8pkHaVz3DAWGlfMLoYGiSllKpYmXkBT0Edu54
            yKoDYQvt/BAUJ+/9gsK+dbWP+GFFPfCNeRwnxqmRjvd+AAnuZzzffYzE+0/Vz/iz
            0M5Hbdiy3xNdqd0w5w+fN+jy0YiY/YUkvwiOcJzFBgYWL+rBJ+g7yW9gKwrCNUDv
            PbjPb8StWEo8uA7gOrePChogAPFciiDkF+seguINcuWhsC0fgyn9KV0KPZ7k0mcy
            v2YsD2cRhkx5go9grloo0BojMjzK//izUk8ldJs3BwPd8+BIq8S2Z5iryw8C3An+
            Pjs6dcyUa3fLJMRCj9xUyzWnwU1MYXJEyzgnt66Cda3OXHiRNDQJVvV912HSiYbr
            PFWvLS/sBR0P6MvHG1yRak5JvLlaC+cJuEIC2jMMeCKnJWSfp4kTzhTMg0niCv2R
            /8QTD/pOTou97ZkEXhGlwOkNKKf7s1IhfMwAac9rr0IemR3/Y012KyD6fNa+5CoY
            SccUH1JkzNDLksBF+tZ4VxOcGDlsev+HVRCF0WS8jPEX8K6lCvaMK9Kvs/R4O2rU
            aAEJAhBGvQo+y+HdJkQyh4S74ykn7kas83S/V0ky3v1uW/r2/HNYqmGDfqINlxiB
            naLiSQu08YN/SwTlkABX8UWF74TPeB48961mDa5inM04NGNzs25Vl468XQoEsb3n
            u0lWrpbmM3OO
            =vnDv
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
        - created_at: "2025-11-28T01:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ//YIhJzg5/zrz8UTvGH8DWFloFitlpNUM8lj6ETrDBCdbZ
            8Pz+dlc/aKuspXSEEvlKTnJ7iMiHEZapbi1Rsh8W+9e6GTetb4JaWPqD3nBWslUp
            fDK3SrHgGCuY9oSHynORfhploUYL/736FqtrQB9llKcDxfYqz+6sx4gIJKPVgplU
            zVUTWIcGGd/Xj31OpkWvqTARK/X6iaLX8r5phQwuonI7HEbihE+ewAPAN3JXTiuK
            kfjTfaeC4RQkHxASYVseQ7TX5C6mUCVlTNQDoo5cOhiLqIA6XAx7xx4vDbhhOPT8
            esq7+1/fINfeXjb4EZsGwX32EN0wok6+/26awdrG4GxExWlnllY+t5s3T0VM5ZjN
            NsOLbfbZF2V3GPkP1ooXX428MYX2FSfwPSaCrVG7hUWLjKJ3pcgo+H3STcL13DSo
            xu9pVOWUgzfdb1gfwOjAmMc/9uMs6Z684C1j+N7YbmuwZXwtBNIWhZLxFug6NWhe
            X7IOvteqEopMiAA0o0cWRryE2N5nbpyY6o1t98xnNDaZaC7aB9CO3+JJh3Hxsb2V
            H+hIdPmswQT/FMat7tYqMb8VauiF7ObBFETFMl15Hfdnf7oeIkRnEwqVxTVyGpPq
            16TJfqDD9iuHSY6sRs5+P2BL4iGd/l1cY1BGxSXrOfejITg8Cb5bjE2/swbS4x/U
            aAEJAhBWXIAuW5T4hDf5p+O++HRIjiBih8L2TJdYTZ2Kwb09fJUn4ggcCGcIFnpW
            bnItm2Y26BHz+0E65ZorfS82af895nzByW4cIau+oQhGX12zi/OE0a3UlavwUjpx
            MN9o7lv5JUZk
            =p1Qy
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
