#ENC[AES256_GCM,data:f10ZQ11pn1gvUtvVcQOFzwBbFnbraN49XFeKCko9UvXmC/uP9LIW5v55rccWvZNbshKE3HfewUQlazA8fJA=,iv:36jZGFEL3uhmpORDPOeSlEIBazUPpOfDQB9z2FovvVM=,tag:eLzMZ85mBv6QrbPX96Uq7A==,type:comment]
#ENC[AES256_GCM,data:kcyakyIQZYN1t3XEC9oDOp+cvfbqdMJdDCFpWgROoTkFI+I9LRpbxfgl,iv:ZguMX0bbMa/1nUCVUJ0d9QS4o0SpmUpaCmnUoJdrM+g=,tag:/6Z4cyS5Sj9HTxqr8cVZPw==,type:comment]
#ENC[AES256_GCM,data:IPw4seyg96iCOcNqpz7YNzbl3qOU9L7xOm0=,iv:RILbY3SHHEvbPIN2rRt2cny3n3ZygtEFMmSmsTm7QtY=,tag:B0iZsIa6eJc8SBxZLMPM/g==,type:comment]
database:
    url: ENC[AES256_GCM,data:ZwL16yqjQHWovPci06MPJh+qI3WEGngwRRIeCs8tPOcvn5qJPnMBb9dsczbSnY4TFq8xTkBgLISaQ8ULXIFB1g==,iv:tiJZPi86BhzLN9HuKeAn0Y+83g743equhG80GjoeTsc=,tag:drFJJguvcynuJUhuTIoyFw==,type:str]
    user: ENC[AES256_GCM,data:tsKwLlM/IsT2obwMJs/jPg==,iv:obxeaBSX7n+rIX4AUI9+hFykROa1nW9rY7cbSl04NE4=,tag:V3YJNk00sf7wxMTH8VI7aw==,type:str]
    password: ENC[AES256_GCM,data:7YJfeP/o6uHpj93/DI7K89ztcJI8Crr2vA==,iv:P82J70MZ5xBogGljA8JE5wD983lcHpMruOUqtKtSioM=,tag:DutDpUMAa9olsGxgUePYMg==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:0xvCzb0NUHH2MqzwLlnBBIvwwQh3sNc=,iv:X4QmD+s1MaZiEoEctfB1aAR6k5HMBVPqGNVuOqfGWDU=,tag:kwgFTHFDj6202d3A9KKZ7g==,type:str]
        external: ENC[AES256_GCM,data:xLW5kxa18HUAYE1Gi4zkojjOdnDTCA==,iv:+zkNibWP05eSQRe66bESMANTLGAFaZBbemxaHmR7IUI=,tag:7hcpl9f7UvWZNGtv0V8V4A==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:VDwzstjcRnIjV+FPK5qVcuZK/A==,iv:xoUO+1cO88Dfzn9FZYUfS0Pm4HcZtyNIDp8J0rF9tLA=,tag:XnUZniP20I7m8bk3M07Y9A==,type:str]
    client_secret: ENC[AES256_GCM,data:F+vNL8rp0nUOamUDa1yJkrrtoOmEcJg=,iv:uong2vQCA5GfpI1jeW8IZfmfC+XrDchLiJ2QLruc+XY=,tag:ShSizdineS+aTVVu3i8BeA==,type:str]
encryption:
    key: ENC[AES256_GCM,data:jSIdpBCjuUsjuUireoILb6XsWfP79YUTzV5STdauP2n85mQ2,iv:gMqNrrOUuzVjfUSu7hiZ8N4oEryeriw4pvY3uM0kvi0=,tag:moJLa1A+66UTWnI32qyXYA==,type:str]
service_account:
    type: ENC[AES256_GCM,data:BbN6sTVfILRgV1j5tgXL,iv:3i+NDWO2JBSPlmDuMR09qJ1VtGERuqcd3upY3/G6soo=,tag:w2Gy8aiNUUhJ6xgovyklmA==,type:str]
    project_id: ENC[AES256_GCM,data:D7/VSNBSb1Z0Fs0sYA==,iv:XHExPrndNpcJNR+HF7GO6l7A5PCcOCxU+2g3B3JiHvI=,tag:9B83NwQhzppDG9kMMyKu+w==,type:str]
    private_key_id: ENC[AES256_GCM,data:8ln1WCTaU5HRFUQxP7tIOg==,iv:vRIzFwDBBvFf+AMvv4F9/ygSSsHga9SB1OCk8h656DU=,tag:lVcsn8P165USniT288t8YQ==,type:str]
    private_key: ENC[AES256_GCM,data:XC1Jg9hRE8ACgc6pvP/powjxFt2+47JAyl0TyI+n7TwJfFXp/XwhLc8XDrcWhTJ8jZe97k6+IQO9zDsHlGVWeQO9ET8dAr+ap3TuYK1k8+ZXlvUgaLZThfUYY9mwEqqq26n7SQ4HPb05qJEYHA==,iv:qv4sbRs7gBnEj7X94wCvFjz3J3ENRFeK5DQyRRuAcvo=,tag:plybANCWKx5TwDCp1r0nGA==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:aM7AxODLeQez8QkUV+zpaZUgn9utWHXN7BchsQrktgQrsMsFG6uNiPP+I9zZz0Gfd76Q/xlK7QGdZZifw4d8vCtrFw2Oz55FDXhUlXkvXXuuhhqbWYjZ5x0iy8BiV0cjGhveb1OzBVBb/OaaANMhZoQtayNwuS4o8x0/DoygU6E=,iv:26hxcZdkwjPj75ykgClY0kGWIBj4Ffz42YZ5azgC16E=,tag:yWW3lkP/cMD5HFbeVcB2GA==,type:str]
    pgp:
        - created_at: "2025-11-28T00:14:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ/+IfAdNKkCbrkx3ZON/ELB7SfZ/f9sG3/nRkdEslGHzATM
            vJseYsTmwPckVzOlfNuseifU/fuvxhevqIsXGbshdMW/9bWNXXFk6II4dboYoJxJ
            70WPVsjYF3KBS08lU9LZH4FZWdYACtnQYmLeyZIpEgLP/Jdua7k9bh774Zb33SWc
            ks7eWRYb3AMAGqX+HND5CDjt+gIJR2HAGVdKM5RgVb1Z5GK0Xq71zSIoAE+R2jmT
            gS4KsNiUkJvWukTXHkeFAtHETk2Q4VG//AIQgJtpCq9GWh7gFw/LiCIseSWFquFq
            ZNFt8aoT4WTPEUJ9L7csykGtACpUtKXJFRFJxnY9plbu+H2Uh4jC0oDRZkvo8YHP
            g1AZy5eZeov2OrYwg2mU8iGm0QgebBPI13/X13vxCWjTbMjgVW0zaQHoZSekmoiu
            GFEI5aMx8Szw4limJhm8kV79E+01NR4j6/UJ03WHc1kARynEmST+kQ8qqiYTvB/g
            ufyrC8ackV8bKLUeKwqHKVHaxZ9PvdsVtZ09nC7m2KA0N4JV6p4vkfe0AdDGKcML
            scj5KCMua0qpSCyrSb+ZlFEj10V78BmbQ39hLib4PcehwsRjsK40p0uDPx7q9rSN
            Co7qoOhW+3QBKync9r9HGh1/sNcZHrAc6mptpRm4KK6UjiFXdQafBhedjsLsdMPU
            aAEJAhBR07mpttnRZWRxZiVdlVjcHCfmuWNMpgeUEU4JzLEain2gHT2l7SgEkWHR
            p0fePK1NAGtJp/12wDl69K+RBci9/UeSosn/cYh385CypWWD+VezH7ubwkV0Mti0
            PHfNbV4+OnyO
            =xMiR
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
