#ENC[AES256_GCM,data:VkDr5NkogAbQ8LNRP1c+NJXHmH50YCNwQqMXUW0sY9O5e6lbpDWyOMZkpv+Vs0/8hEbUzr1Q+BxfusqW,iv:uF5moFwHU+sg6pJftVc9BXs6V0+xz+mUIz5/jOOcKOU=,tag:G8hj16jHajC2iZFsam6R3w==,type:comment]
#ENC[AES256_GCM,data:jRJAbrGRPVItmNibT33o3oCRt4dYTpaSuJA0n/4Fb2FJUz8MgO8IycAi,iv:fIalWvjGyqGX4HGRIkTYfvIkPDDNUdxazSVzgaJGHLs=,tag:NCngfLio32fqZcngcFiGGg==,type:comment]
#ENC[AES256_GCM,data:VNZsCmZs3yiHS70KvzHOLx6XAHDsEfLlvUA=,iv:NROJEOmmIOiQNPfVfmPQcowFU1q6v4mu0tcJTiRM3qw=,tag:pNONF/mog0QwJTlPIGFS3Q==,type:comment]
database:
    url: ENC[AES256_GCM,data:C14NndWiPHZJBWmESPzCYyg4kfqvLAtQXk7taBkakbN34wMkYIJg0URNc3yZPUtklWeCgViaaldJXXli,iv:dh4eNSNu8Q+tFpjUTm5L53LmQ4je/A1/06uUQq4vHhA=,tag:W7HPxjDaYFLXuNz7gG9iXg==,type:str]
    user: ENC[AES256_GCM,data:WTfNLQWxvDFHEZ3Fllk=,iv:2Ql9ljNABO/UR/HsDKgGXeWz6PWyODKAh2lCCB53Ew8=,tag:2VNHv2s1EgW9H+UMPQk5Vw==,type:str]
    password: ENC[AES256_GCM,data:29U41CLGDMuLyHFFdspnokBLunig8vk=,iv:WHkH+Id/wQQpsNme912xfUQxhb2glQcg3FXv+DBsOxs=,tag:A/vAedyt/uxglwrjREjwzA==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:pGrvW3taAU32F2jwxnmfe8iM8wEN,iv:q5L/Ybf6OA1/TJfiom14J3eNZji939KpPTeYDDkWz/w=,tag:YAOkflIdlAyQx44PZkEfEg==,type:str]
        external: ENC[AES256_GCM,data:zTneQQKyURpYdNkUaUhInDoL8HM=,iv:BgGsH+3BhNXlZRHexrxzEvwWok/JhdQKKrUHBuBA6pM=,tag:xCyfQRQh+wzbkbnz46dehg==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:F20N9lszui/Td3TDImu3Uo0=,iv:r99tOsgVYn4aSfxOjL7flfOGc/MB3rIcgR/i6ZsOmc0=,tag:1spmgGmOOoRC18g4myIR1A==,type:str]
    client_secret: ENC[AES256_GCM,data:m1IcFB8VuiQigxx7QFDT4So8LJmo,iv:dXhLqaLffe35WxzRj/HcKwNh4xpA1ZQTDGlVT6Ui4Xc=,tag:juq4H7fCcWUzblUI8bqung==,type:str]
encryption:
    key: ENC[AES256_GCM,data:tO1H+13nvLWhjwp/vti/u2o8nXhb7/FQuTWdUAZzSM7axA==,iv:j1r5wDbI7fS2MTw2Ntfoca/po20mf3u9Re4W0fJaClE=,tag:xsr/kywBJNuHj/m29//bsA==,type:str]
service_account:
    type: ENC[AES256_GCM,data:3Siy7Y25lEbsOQkJxH6t,iv:SJCZ8WS65Wgf9AuuCOnyxwuhvOSdzjrvfyFxgysdb8Q=,tag:zmVrrfcLo88NCl/B1PQNUg==,type:str]
    project_id: ENC[AES256_GCM,data:fdERpqseYFvDYu0=,iv:by7+xvw5aaeH0x/794njZJynCLVWEtxyVSYsmVZy7Xk=,tag:rMYKK4xExKTfpBs88lvdJw==,type:str]
    private_key_id: ENC[AES256_GCM,data:Kl6NcJFeZN1o2p/GHZY=,iv:LvEjUaG34AagxbpOwxJahOxbxzBA5dGcASUn33y0EcU=,tag:XrBScMZDx2CrK2O9P3Iz8A==,type:str]
    private_key: ENC[AES256_GCM,data:OGq2iq+ktL2Wa0n4MmQQhOM9JT9QjrGQpBa6l/+XYyuPPeZPliSEyePfy23Ug1xTF1Ta49KqWPv12s9JuAroP0iv5TUFQDz+ufjLATdcM3tF2jIWnVT32EVHMyHQx19QIvfoG3/F9SC+ehEZaw==,iv:WVt7v95mKJAvxedDJHQoLPHBhjo9Y9SkUxetMcioxs8=,tag:w5aZjs/mXaAl7UeXoYfixA==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:JnlsaM3d5mk8LJItvq7+co75b2auRbNNu4bDHxvXVGIJa2zW/1ObexZjDQlfAruCxtujL0hQYDgSaA6mjMCZVJ2ZurrNY3T1WcfzEg6MC5EAQbetlGazvmYssbimTjd5PX5qinPYTCP6p2mlzRXMdnuOCXO3DC6weIvuL25geWY=,iv:rmRqbazC5cp9sUHq9R5cTcx8zX70/YopwFwzfRUL4F4=,tag:HzTqdYeiii/fPGib33GuGg==,type:str]
    pgp:
        - created_at: "2025-11-28T01:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUAQ/+PQTPCbLrUOwgHm5+66h2EQVCZWYFrC+X8UVENGNhrXoM
            dtNjopB/kXLsNJ50sj77hKa/60Hc46A3VXp+AwJNnzsQRhxDz2k15HXBGViaDf4H
            ZVbJZY05MQRUz3od4b9E6ifpf7p3QYNvSHPG4jF59xrwoV+Ql6AsBbePVGyJpVHX
            9iOc2YqlAgdXoMetWxmgsQZwJO9rThdr+Ac4j2OWcoUQ4MYmPXz5b71A2P88kwWL
            n6U30AEzUVQtOKJs0Vqjz6HcWk15p3quZhvYaOSxXJoQOmBXpxTkUUVdMjSMM/oT
            XFhYCBu/7ibL4cqILByvHq21N4k6PPHeNPGUJ2l+WI4yUlXOgBDeYmk/0qDY2iuR
            UuOF64JZrOcsQ98d8rtqJFQYuhf/LROiVNN/RtmNp+Qeckm9pfducEksoPCjPPas
            qffW+JX3rUMCdgQZMtOfv9PnBk7HMtXdiW+o9XsBjriWsIO/O4y40Z7YDcd+U60f
            x6IUMOju0SeIGbSe0tjpHu5TP2Ox5mo+VmLWjVkY2VRXrTxkiZ3CWLti9OTssS5J
            Bf+rXCe3dXimlsxaJ5sbkDxjkktSopCkGl2JjPp7GsDbtN6tCGcUNO0+J/ScJCKf
            LG7DRci1T4lDg7p8Rfft1IktMzTjqD9vXAz9BtN55sKEFt2JWMOXLzXHfQuSGiDU
            aAEJAhCRttQWd60P8BMhpclMvG/sHvxByqsP9PIxI07rX4MtLZjmEqHtFWXZmqUn
            m3VyBEEzJs9RorzaEK6HIgSD7nS7iedj/+hFJyfx8eYZyRpejHSFfMl4EjVcCB9C
            /SP8jTpHcYVK
            =gkjg
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
        - created_at: "2025-11-28T01:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ//W26vdsSrTXi6E2x2a8wdB+uzrSEXqEhBBWq0oN/hQml3
            SfdDcNzb49/58Wuh73PfPKDGR4o+WsrFHmiSwNsP/pbK1FQ8ijt1x+9zHcv1CK27
            5Ib/qalQmrK2e6Wx8i+ouhh8wBco9NsxiiXcUqtebmqYQFY4EMcpwFLXIIyAWBWQ
            fH7UjyZ7VkfOV0PE4jV8kZB71FJpDyWztcXj4cCYd4hxviirEcTYT+O7Qa/ZkvsC
            W8WFzO521ap7wiEChBUUmrfWb+b7SJ02HAihv23Z6jGvFOLAMXBXcj8IK+wmh7XW
            UqcmVqpF5jdFOD+lksoCsaddPoB9BiaHdDvrlvJ2UC0kUpdF8BAXyb3esgPuJCiZ
            aXdMxKQ9SZFr7ZLgoo8ICPjG370lYRFsH+6NWGtc1AaPyz9aS0vFPpFMvsDViRx3
            EGYBiXPGxNrlxwBijH4H4h+3ctjuBNAG7UZL8IPIbKeJ6jUrnEHW+NnN8dnspTAt
            tSqTWrPamSJdV4LXFwAoWpcCRltpJPlG9Zr0LFSrnq9tKoMgshl98b8EmdG3OzgV
            ARdVpLD7g4Ps5NYbhHuDHRiF6wUOyJftSx9II0rSM0gFPbINModMO2JUQACYc8gO
            gQunjdDfSI1ax2UR5kLhW27iWwBZeTOtwaYg/ZJ9JEaWSKSV2eMHiZwEqq0Z1PfU
            aAEJAhBjnu+9zHcJrzsAGTtckgAgc8v77D14bHSU1Nrwfzp9lSkhhqIlmUdBdzei
            cuIb0rfoc2PzV/lNoiEiJVMvKj0jkTbxRPCtWrW/wXEgZwnmyn1EspDphxQkMktB
            NRO/Fd564kmY
            =w9jJ
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
