#ENC[AES256_GCM,data:VkDr5NkogAbQ8LNRP1c+NJXHmH50YCNwQqMXUW0sY9O5e6lbpDWyOMZkpv+Vs0/8hEbUzr1Q+BxfusqW,iv:uF5moFwHU+sg6pJftVc9BXs6V0+xz+mUIz5/jOOcKOU=,tag:G8hj16jHajC2iZFsam6R3w==,type:comment]
#ENC[AES256_GCM,data:jRJAbrGRPVItmNibT33o3oCRt4dYTpaSuJA0n/4Fb2FJUz8MgO8IycAi,iv:fIalWvjGyqGX4HGRIkTYfvIkPDDNUdxazSVzgaJGHLs=,tag:NCngfLio32fqZcngcFiGGg==,type:comment]
#ENC[AES256_GCM,data:VNZsCmZs3yiHS70KvzHOLx6XAHDsEfLlvUA=,iv:NROJEOmmIOiQNPfVfmPQcowFU1q6v4mu0tcJTiRM3qw=,tag:pNONF/mog0QwJTlPIGFS3Q==,type:comment]
database:
    url: ENC[AES256_GCM,data:C14NndWiPHZJBWmESPzCYyg4kfqvLAtQXk7taBkakbN34wMkYIJg0URNc3yZPUtklWeCgViaaldJXXli,iv:dh4eNSNu8Q+tFpjUTm5L53LmQ4je/A1/06uUQq4vHhA=,tag:W7HPxjDaYFLXuNz7gG9iXg==,type:str]
    user: ENC[AES256_GCM,data:WTfNLQWxvDFHEZ3Fllk=,iv:2Ql9ljNABO/UR/HsDKgGXeWz6PWyODKAh2lCCB53Ew8=,tag:2VNHv2s1EgW9H+UMPQk5Vw==,type:str]
    password: ENC[AES256_GCM,data:29U41CLGDMuLyHFFdspnokBLunig8vk=,iv:WHkH+Id/wQQpsNme912xfUQxhb2glQcg3FXv+DBsOxs=,tag:A/vAedyt/uxglwrjREjwzA==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:pGrvW3taAU32F2jwxnmfe8iM8wEN,iv:q5L/Ybf6OA1/TJfiom14J3eNZji939KpPTeYDDkWz/w=,tag:YAOkflIdlAyQx44PZkEfEg==,type:str]
        external: ENC[AES256_GCM,data:zTneQQKyURpYdNkUaUhInDoL8HM=,iv:BgGsH+3BhNXlZRHexrxzEvwWok/JhdQKKrUHBuBA6pM=,tag:xCyfQRQh+wzbkbnz46dehg==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:F20N9lszui/Td3TDImu3Uo0=,iv:r99tOsgVYn4aSfxOjL7flfOGc/MB3rIcgR/i6ZsOmc0=,tag:1spmgGmOOoRC18g4myIR1A==,type:str]
    client_secret: ENC[AES256_GCM,data:m1IcFB8VuiQigxx7QFDT4So8LJmo,iv:dXhLqaLffe35WxzRj/HcKwNh4xpA1ZQTDGlVT6Ui4Xc=,tag:juq4H7fCcWUzblUI8bqung==,type:str]
encryption:
    key: ENC[AES256_GCM,data:tO1H+13nvLWhjwp/vti/u2o8nXhb7/FQuTWdUAZzSM7axA==,iv:j1r5wDbI7fS2MTw2Ntfoca/po20mf3u9Re4W0fJaClE=,tag:xsr/kywBJNuHj/m29//bsA==,type:str]
service_account:
    type: ENC[AES256_GCM,data:3Siy7Y25lEbsOQkJxH6t,iv:SJCZ8WS65Wgf9AuuCOnyxwuhvOSdzjrvfyFxgysdb8Q=,tag:zmVrrfcLo88NCl/B1PQNUg==,type:str]
    project_id: ENC[AES256_GCM,data:fdERpqseYFvDYu0=,iv:by7+xvw5aaeH0x/794njZJynCLVWEtxyVSYsmVZy7Xk=,tag:rMYKK4xExKTfpBs88lvdJw==,type:str]
    private_key_id: ENC[AES256_GCM,data:Kl6NcJFeZN1o2p/GHZY=,iv:LvEjUaG34AagxbpOwxJahOxbxzBA5dGcASUn33y0EcU=,tag:XrBScMZDx2CrK2O9P3Iz8A==,type:str]
    private_key: ENC[AES256_GCM,data:OGq2iq+ktL2Wa0n4MmQQhOM9JT9QjrGQpBa6l/+XYyuPPeZPliSEyePfy23Ug1xTF1Ta49KqWPv12s9JuAroP0iv5TUFQDz+ufjLATdcM3tF2jIWnVT32EVHMyHQx19QIvfoG3/F9SC+ehEZaw==,iv:WVt7v95mKJAvxedDJHQoLPHBhjo9Y9SkUxetMcioxs8=,tag:w5aZjs/mXaAl7UeXoYfixA==,type:str]
sops:
    lastmodified: "2025-11-28T00:05:12Z"
    mac: ENC[AES256_GCM,data:JnlsaM3d5mk8LJItvq7+co75b2auRbNNu4bDHxvXVGIJa2zW/1ObexZjDQlfAruCxtujL0hQYDgSaA6mjMCZVJ2ZurrNY3T1WcfzEg6MC5EAQbetlGazvmYssbimTjd5PX5qinPYTCP6p2mlzRXMdnuOCXO3DC6weIvuL25geWY=,iv:rmRqbazC5cp9sUHq9R5cTcx8zX70/YopwFwzfRUL4F4=,tag:HzTqdYeiii/fPGib33GuGg==,type:str]
    pgp:
        - created_at: "2025-11-28T00:14:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Fh4KnHKmaSAQ//eAGM/AG75l/XiOB2U8Cz1drUR0nS9hcD5yt51+xtmF9j
            yh+Cn8yFNXVui+WytV1Wpey7B5g8d6ZfY7cHJPOVkv56Z+QREl1UG2Mk9HYSIa3+
            avljjbgyL3CV+IdIM3tAOHtbXD+dIb+ALB2ZP6Nv7HtAx57OBlfWuyvRxNk3QLxo
            GZH7NVW6zuKi55dgPeyhL5n7D5YxkuiHv3duA8lBHMlvQ2da7s0heOEdJ1tUxX1p
            bZ5JXZ0uTOf8S84SAcQcc/frj2alJN50gVeVTztI6dzq/OoZ8O1PuWHzOhTPeuEY
            9I4sN8XVQdcgq15gplbk512ZIVHzEgEdI7JVTnVGw5DMWOKHwuwKNBWxOrVP6FSH
            gDuY4VDYjJ0eoWFNDVhq9l22TPBFqbeJGAwODawfShySbHCc0q3HF6dppVNE5CUH
            Wiqf8kn2uYcNBOVr8SnMZ4K27TOUgwiOGWeD7eWUkKknPzaICU66hNB5K0Nsh1GW
            UZPRhq3mg4Egtku6oRZ0sRztjReEiCSnmem5KWdKrYW6SGnKMS7ZAZBi9F//mgnd
            4B0mB2k8ikUagcqr20Ev6jiCsXIjAHXhAuThkIoPcbpg9jIk98to+moX/EA6ppeQ
            5OA//mIB7qh0qcpfmtmQUBC86uQ63Ct5nmlEP1Lv8OcXtLQwDQ2oHwT1szTcqbrU
            aAEJAhD3Ksc1OkXdskVcjyo1/bdyAfNwiJdjR5BLwF/0kIJnIL5MAUl1adwSqqgs
            5tpQeyqYwnyeaiqQPGCd/iwz8wz1P/CgTHOS2prnfYig5uJ2OJYu+ipzAnbuXXlq
            r7Zo5qYZWbGT
            =LDpq
            -----END PGP MESSAGE-----
          fp: B9C71A2FEFCB2AA3F228996EA161E0A9C72A6692
    unencrypted_suffix: _unencrypted
    version: 3.10.2
