#ENC[AES256_GCM,data:aguK0RAScAPFnVFT5d6ChYdHqQ0oFTr+dIPen4/LGQU/yU+9ACZ6ihDNf596JwBhljTSaYcLUpvAEOw4,iv:Jf+f5Yb7qydijPwlZb29dGhRENepo7fE0fJc/VC6UPU=,tag:xlx/eX/M7yDLOqbs6FG+XA==,type:comment]
#ENC[AES256_GCM,data:22gYz9+YGlfwYQSNpHcQyvvTXZQKNpD6N4Tvwo0pTzFHb+lM+7SDEaew,iv:7nCV4LuX/33dU6TC0+/EHKzQuXyFjY7uNn2repbZ+Fc=,tag:e2Os1dgsQ93zuLIvOwhZZA==,type:comment]
#ENC[AES256_GCM,data:9VKjskJli7z3WHZLT8ztb2+KCEpWCBppjF0=,iv:GXaPB6qeDhS7uwYsBqfw0BHIygZnLMdC2+p6LgSqU30=,tag:kxy+c8zpExY4FT/N9spPJg==,type:comment]
database:
    url: ENC[AES256_GCM,data:AbclgpKcPzmQ86i+S1NcbzXm3W3VIHhBvdfW0LXjSnp7hF1UIWYc22I5cvILCZPm0yseZ8g4W9JyCiJU,iv:rfzK5g5I+B7gwa50pgTPWsslNn0eeW3qUeONBe8TysU=,tag:bsnSjh2cfSHlNWlWLHcjWA==,type:str]
    user: ENC[AES256_GCM,data:IeN7aBxlCRteNzmrmz8=,iv:DgyJLTIROcirVuPA4Gd+GB6L3P0RNrwPYACc7BTqg1U=,tag:RldULv4h5TWQykiedb7ohA==,type:str]
    password: ENC[AES256_GCM,data:MJBtbCpmREH2eDH187z/dL0W1BbUCvw=,iv:CCelWF5W7okAR2Y6XvK4PvdRjoQJCvfWUrc7SDm8+Y0=,tag:CT9mOYGVjWcGD+LkOVQ3qQ==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:tAS/ExoBysfovLfkgFBEnplrzG3p,iv:2yFGTjCDf3fJjb+7u/el+7g2uyONISWgkV5mcuPXxaE=,tag:qojb2Mz4IwhN32YEOLeStw==,type:str]
        external: ENC[AES256_GCM,data:ko1wf8jlxby7moLq/X7js4+tva4=,iv:jY6/jABUUjwu5FIN2R5tze53BCDRhuyrjzHl4oJUJAk=,tag:S27/Ab4F2H4DiDEpqtK4gw==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:hnTVOXlJWaUn8paIvxfW0QA=,iv:Wg+gURSfdnwh754DBiO+J48/aQwHji/SSLQxarXj+8s=,tag:PC3CZpPIU/lytxiOhwrY3w==,type:str]
    client_secret: ENC[AES256_GCM,data:K/9o5q4Gjhwqvf1wnRSrj7VISzcF,iv:4kNd7q33ZPw4ald7X8AdIlnynt1cikxutATX9GBPhJ8=,tag:FDZ8YQdFUW9EqZm4C8pK4g==,type:str]
encryption:
    key: ENC[AES256_GCM,data:Ym07gxUcnLjLp/853OKi09RRRfP5vSkYLthPe+d7n419sg==,iv:QYSn+xZJpT1HhnyMZn89yQhYgXGk2OjqKEjNbPIUMus=,tag:FPIz9uKnrv7m7pZIrXGLNw==,type:str]
service_account:
    type: ENC[AES256_GCM,data:8L98YoOJFQNpbUEpHnNJ,iv:koNdEJlK8TtvXfA1HWsXeMfqiTJozBji7PKipsOpT0A=,tag:8TATtMG5O17wxv3FS8YDDQ==,type:str]
    project_id: ENC[AES256_GCM,data:bLfh2aMhJ55A0bE=,iv:Cz6ximf7avbCdJEslrWJSsZh9Z44XvEoqLUdYXY3z5Y=,tag:TeT05KUB1qeu3JOBU2gUng==,type:str]
    private_key_id: ENC[AES256_GCM,data:Pocmk3Xpu7SRNHZ5ceg=,iv:Eq6+p1k66fUbzglA1QjDVT3TS4Q4n2W+l4lVArzzGjY=,tag:l1ZqtHSLLPpwtPT3iVhs1A==,type:str]
    private_key: ENC[AES256_GCM,data:GTwpB7WB4E6F/qoQ2l5aEA6DK4gCEttT9SQww9QSwGEjalSy55H6BEn0RhcKu1iUC7knmgxoJRVFGkqwbRZi8uCu3J+XWDyKaYI5OrzUcT4aQcHaAdu02LnmIFi3wft9RW77uzvQxgC1sgkb6A==,iv:WpjILEWtBCliZJSND0n2vNSmSaXd9b+dsl3oRrBqCNg=,tag:necQRk/dAPCgXteLjmoAmg==,type:str]
sops:
    lastmodified: "2025-11-15T21:15:40Z"
    mac: ENC[AES256_GCM,data:a+qDHwVKdJeJZsq+nO00y85o9ES82CkfMqZcFJxcjmnhsE0jFp6kjOy7DsyV6g4IKFV7jyqCdvEciWB1wSHaw1WltAcfeRi0G11vX56q/EYTnT8Al35tZCZ+Z1EaVn3VYdBTRsGolnjc7geimn9oEwSRtbV/G+BM64c11zNuqVw=,iv:GAmmAhaXFOc9jz+jRP0zQ3VGN5anpOVr396fUq8W1Ww=,tag:nFuBIrLV8D+b57tiWyEouA==,type:str]
    pgp:
        - created_at: "2025-11-15T21:15:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUAQ//bjHmvkPARa8ej4uIi6Vy+zjPthpcQmaHzlVrx3Pf49yr
            n5TpG20za/UennkGMRjrqeeJ+SXajwHxQTf4UnLk/TZObmUnq6b02w07Ww8/BmEU
            yEesS5C8teW5lu1ZzdiUZcjza4bAwsGRtLl0AvTKh+lE99Z0WQYoKOXbYpVtc7Sz
            RysPbH82QnUlokd39zxSovaEyBKzh/SCe+nlH9sOemNIeaAOwHB34QxIeHG7VzWJ
            NHFGYavn7/7wtOwvlH6xKRUQTMGRN30F0CGKsM+uBk7PwcdnPSUsc1bjw50JDKGg
            EOmHg7IbM1mIo/X7cX9OcQDk+I4sKBBDBN2MR3A/1WXKUGJN0KMol0LT8Gtxat3a
            wfPoQPlPZ3kAXbDCCpP33MZ7or8W++0lfM3aaV7yWjQZqj572SJqgv6IYp1d2/Ok
            s46GypTh8FQojcxSf0VKifVpkpmtu0cvS3Tkb9Him0XzrqCDDG0QmCmQcL128mdA
            OGLug5nHaQFuQvrzT1lxxvj4JI1rggDmx4k0npx29AGw71fTiSpJ9CCPkssHBJX9
            KK3P7UdGtH1fvSCxwA3AOfUoF6zG4J2XPv70yJtYsnd7K/kS7B4GrlZBT0J6DF3t
            LEjOduSHTy5w99brfL0IqFAVgLVF1DlKG+oQFdbELyvaBelpXkr3I/I082XahqPU
            aAEJAhC26XuTaT9/Qo2td53HM+q8QyK1e+JfDHH4Xnn2olMY4/gwtQNRdP46BAS8
            cl1n4ZxU18vU103WrBt2NPjCmvotdOoLjxMB27csVG+EuX/2Q84qnq5dZu8x0a2d
            LEbD6CgZXG8H
            =2b3J
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
    unencrypted_suffix: _unencrypted
    version: 3.10.2
