#ENC[AES256_GCM,data:wkqcsa4s9jLTgN4yfQFr5/+C70h5mLsCc1FnLBCeD2M79BCnvFdBHZsn51l9NR5X5OTp3uF4RstLZ/hrOgA=,iv:36jZGFEL3uhmpORDPOeSlEIBazUPpOfDQB9z2FovvVM=,tag:2aquCGiue2eYmBZIZciibg==,type:comment]
#ENC[AES256_GCM,data:zwCnNCnInHUU+oeueuAX2y0/lHM01glTWmPrz6GooXN5UzPmGBilTabj,iv:ZguMX0bbMa/1nUCVUJ0d9QS4o0SpmUpaCmnUoJdrM+g=,tag:17tK49HhcJ4utlupP3ByFQ==,type:comment]
#ENC[AES256_GCM,data:FG513TFlpar189PYjWked8TEpG+Q7knsdFo=,iv:RILbY3SHHEvbPIN2rRt2cny3n3ZygtEFMmSmsTm7QtY=,tag:F/2mfBFgxP76ulbDsZUo7w==,type:comment]
database:
    url: ENC[AES256_GCM,data:nuPHQhIKryTjSnYf2+vKobn7n5qs84+8WyUkKeQZX3gdTeOEHWT0jlgTyK4GZM53mgxBnS9fA/zpUhJVF1DJjA==,iv:tiJZPi86BhzLN9HuKeAn0Y+83g743equhG80GjoeTsc=,tag:70bbHw6EaAY/HZHjvg6mEw==,type:str]
    user: ENC[AES256_GCM,data:tpg6Ae3Z0mlUBxlwBkNXtw==,iv:obxeaBSX7n+rIX4AUI9+hFykROa1nW9rY7cbSl04NE4=,tag:9KCG1CxHXgefYO7FrA7KTg==,type:str]
    password: ENC[AES256_GCM,data:nzfJxe5WePyNBknlkkR5iqGggI4sCjeFVw==,iv:P82J70MZ5xBogGljA8JE5wD983lcHpMruOUqtKtSioM=,tag:NKe30y4go0lf16lZCarFgw==,type:str]
api:
    keys:
        primary: ENC[AES256_GCM,data:Q/23gdRoISxHAPb+z2hIvr1xb47Dxbs=,iv:X4QmD+s1MaZiEoEctfB1aAR6k5HMBVPqGNVuOqfGWDU=,tag:0h3DwzdGTYkxCjAU3w2oAw==,type:str]
        external: ENC[AES256_GCM,data:7rzmPSJVrxm0+eIAIGiYD17DSVZ8Jw==,iv:+zkNibWP05eSQRe66bESMANTLGAFaZBbemxaHmR7IUI=,tag:dPhhqf98tTFsGuZ3NtRWnw==,type:str]
oauth:
    client_id: ENC[AES256_GCM,data:AgbOpNC+rPL+7F5bI4tjUlKc5w==,iv:xoUO+1cO88Dfzn9FZYUfS0Pm4HcZtyNIDp8J0rF9tLA=,tag:eBvO0wOXm7WFxXkj4gexWA==,type:str]
    client_secret: ENC[AES256_GCM,data:iWAU6z2p63WIwxaMekGssPU+CWk0rfI=,iv:uong2vQCA5GfpI1jeW8IZfmfC+XrDchLiJ2QLruc+XY=,tag:69VrTtJ7Ed0v4TP0YZImjA==,type:str]
encryption:
    key: ENC[AES256_GCM,data:Xkqcu2rPj7saG/TZ6oYX9xUCFDFpyw8QF3SjW4RiIznaC1vi,iv:gMqNrrOUuzVjfUSu7hiZ8N4oEryeriw4pvY3uM0kvi0=,tag:+W57+lnLgDDYFON6fikjlg==,type:str]
service_account:
    type: ENC[AES256_GCM,data:tQsVKyXibsfLX67UtOxk,iv:3i+NDWO2JBSPlmDuMR09qJ1VtGERuqcd3upY3/G6soo=,tag:tZuaFNzWh/ZB1qIZB7XOCA==,type:str]
    project_id: ENC[AES256_GCM,data:2tpDke0ipiQb3EGAeA==,iv:XHExPrndNpcJNR+HF7GO6l7A5PCcOCxU+2g3B3JiHvI=,tag:c2BSXUhbntBEJdBykIbynA==,type:str]
    private_key_id: ENC[AES256_GCM,data:Byl/tuVNSjvQjiAMotWNGA==,iv:vRIzFwDBBvFf+AMvv4F9/ygSSsHga9SB1OCk8h656DU=,tag:BzUhJdeZrjVNzmsfuINv8w==,type:str]
    private_key: ENC[AES256_GCM,data:uJLj3G9T2ufzHzRWXbAhpCcSZ6z3h/dCqnp4kBsowBRxtoDtMEBT/LotaWN+f5gltuSgX8FeqCL3+iUm7IshQBL0KeNBtXOOvMStexA29u637syzpltyQT5w0wSrtxjPe4MUGGZqDT6v+bRvEw==,iv:qv4sbRs7gBnEj7X94wCvFjz3J3ENRFeK5DQyRRuAcvo=,tag:4St+ztKTvzAgUqH/KPVKyg==,type:str]
sops:
    lastmodified: "2025-11-15T21:16:37Z"
    mac: ENC[AES256_GCM,data:J57sNB+KOHVRKzyTD6em3q/u5xNBuRC89ECYM2nP+iOXKlT6T7rqPYC6CP4uU3isdUZS+t5KzJoAxwqf2lyMG5oYg79UxUManwiJDgWkzXvUETcGjn0oXZTZ6D6apWt8IxVM7kv1k1sqXHnNN/BmOh+7euKns2dhB3Ltn41vIcw=,iv:QjcI49xJARkY/I3xw7sf4zD79rFiLPVdu8tR6LEDvtE=,tag:IIFFv4JmNWt2T5rs5R1wnA==,type:str]
    pgp:
        - created_at: "2025-11-15T21:16:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7wtaE+Nz1zUAQ/9G9UnXJ40/i2eSoSrjqShmAXk2aHcKBPCe4pMcWuU6iNp
            VercnHtztscm1f/xUpGWGAVHeiNCb9vUBsvyA6B1HFTfWuQhfnhHgthNpQ9V9+C9
            QfGKpjTCbOQ1vUPI65CCy4DsdJspkuuCx9xrYh1+/URFebCSP3ZEqNwxpwCYHhVA
            ji9vtL9/TLkvQKAUhIF0izQGKYwFD7U0w31NEU5pjnC7LnVo5RbmKA2SSCstApFz
            NUVMDHN6seb4X3ChBfsxQht5aBlDnUTJpUM0b5PVe9daOk/PZhd+yA76bqlTKzds
            RUeXWtvxSLS04dV8OGwsBHRc8ngyz1PJVba4YVVWoKO0Upm9zFgdIAEnhf8tRC1U
            O4iSWN0lHcWAfCFxK0xOa/mnfw0IGLCclLOJGDpYy3E8ysDkrul60TR8PEbAjThD
            QWDtp8S7dFjr7tXh2E2ujnyG782J3/07bwvMy95WpGsHtBt9ivP/dDXi1qYNI62n
            hSbwrrgZ8yRdSOnFWA34TRYo//nOC9SB1+Q/6LulnAliMQDLSr7HuYI1pnSc4Vto
            7/QrRh/hlbeaZUPjpYldt4L9Cfr2We4vN945uzFeRMJTgvSDvLJx9/F1sBx3ULI5
            hjV1nLmBiApVLEv8m9Aocgdu/5UjbAHAxKZ4Y8SRlxNu4RYlGipzxcCCCR1xDV3U
            aAEJAhDix2msiCYZXR1+RMa+ReDLQdEFCFopyjkcTy+nZRBL1o9ey3605/J+7j3v
            vHO6NmR2WEm5IHkVkqe1mVYPi1d293mx3IdiXaudvTjxP/E++wWHI4rZyHInqdIM
            bGP+5IWBpi/o
            =oWqR
            -----END PGP MESSAGE-----
          fp: 564F22B9BCE625AC1A935A10BC2D684F8DCF5CD4
    unencrypted_suffix: _unencrypted
    version: 3.10.2
